version: '3.3'
services:
  server:
    container_name: coolgeoapp_server
    build:
      context: ./backend
      dockerfile: DockerfileDev
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: coolgeoapp_db
    image: visancal/coolgeoapp:db
    ports:
      - 5432:5432

